name: Play the Game
on:
  issues:
    types: [opened]
jobs:
  startGame:
    runs-on: ubuntu-latest
    steps:
      - name: see event id
        run: echo $EVENT_ID
        env:
          EVENT_ID: ${{toJSON(github.event.id)}}
